### PR TITLE
Added per200 panel rotation code

### PR DESCRIPTION
**Pull request by marcmerlin**
I've tested it, it allows panel rotation by just using an existing switch that has another function and switching it quickly to any other value and then back within one second.

For this to work well (it can still work ok-ish without), it's better to set SR1_RC_CHAN 5 (although it can work with the default of 2, it's just more picky about timing). If your OSD board is plugged into serial2 instead of serial2, then change SR2 instead.

### CODE REVIEW

**Comment by marcmerlin** [comment]
Is this very good for you?

**Comment by night-ghost** [comment]
I don't see any difference whit prev version.

You code for "by 200" is now accepted to v934

**Comment by marcmerlin** [comment]
The difference between the two is https://github.com/night-ghost/minimosd-extra/pull/195/commits/8cb3a2bd721069052ea2f35b033488780fd88af6 which reverts things you didn't want to see in the change. 
The full diff has fewer things in this PR compared to the previous one, which is what you were asking for I believe. Hopefully that helped.
Thank you for merging.

**Comment by night-ghost** [comment]
Hmm. I already said that problem not there but in build.sh
before it was
```
make_one 'UAVTALK' &&
make_one 'MAVLINK' &&
make_one 'MWII' &&
make_one 'NMEA' &&
```

and it stops on any error

After your patch & "revert" it takes the form

```
make_one 'MAVLINK'
make_one 'UAVTALK'
make_one 'MWII'
make_one 'NMEA'
 make_one 'LTM' 
```

so now it skips all errors and continues to run.

That's the place were this PR break things.

Your code for "by 200" accepted and is in new version, what else?

**Comment by marcmerlin** [comment]
Please accept my apologies, I don't understand what you received on your side. When I look at this pull request, I see
https://github.com/night-ghost/minimosd-extra/commit/8cb3a2bd721069052ea2f35b033488780fd88af6#diff-0b83f9dedf40d7356e5ca147a077acb4
which reverts the file like you asked re-adding '&&' at the end.

I don't understand how you got something different, so again, I'm sorry about this.
Thank you for dealing with that (or other) issues and taking the patch.

**Pull request closed without merging**
