### PR TITLE
Added per200 panel rotation code

### PR DESCRIPTION
**Pull request by marcmerlin**
Yes, I feel a bit stupid that you added config support for this for me ages ago and by the time I saw it, I wasn't working on RC anymore.
Until now. I'm back into RC and I added my code I wrote a long time ago and that had been missing from your tree.
I've tested it, it allows panel rotation by just using an existing switch that has another function and switching it quickly to any other value and then back within one second.

### CODE REVIEW

**Comment by marcmerlin** [comment]
Hi @night-ghost can you explain what you said I broke and what you would like to see changed?
Or can you merge this and revert what you don't like? (which is probably easier)
Thanks

**Comment by night-ghost** [comment]
for example compare original build.sh and the one after your "revert". So PR even shouldn't touch files except that you try to fix. 

PS. to build for one protocol there was 0-build.sh in MinimOsd_Extra folder. Or just say "make" for MAVlink

**Comment by marcmerlin** [comment]
@night-ghost , thanks for the details. Note that there were no visible build instructions, making things a bit harder to guess, sorry that I guessed wrong.
I am proposing to change the build order for build.sh, which is why it is in my PR.
I also explained why I'm proposing this.
You can however disagree and take my patch without this change if you don't like it (even though it should be a no-op for you).
You said my change breaks things, are there things I broke outside of the define I had to disable for the build to succeed?
Either way, I'll say again that I'm totally ok with you doing a partial merge of this, you just asked me (a long time ago) to merge my code into your tree and send you a PR so that you didn't have to do it (I gave you access to the diff in my tree back then), so I just did this now. Again, my apologies that it took to embarrassingly long.
If there is something specific you'd like me to do here, let me know, but if not please just merge the bits you are ok with and feel free to drop the rest.
Thanks.

**Comment by night-ghost** [comment]
You definitely don't compare files which I asked for :( 

PS. I could merge your changes by hands to not break anything but I don't interested in this changes because I don't use anything like. 

PPS. Rule of thumb - copy cloned repo to another folder, make all changes in it, and after things goes well just copy needed files to original GIT folder and then commit&push

**Comment by marcmerlin** [comment]
Ok, just to be sure I don't have to waste your time doing this multiple times.
You didn't in the review say what you are opposing exactly, so I'm going to list it here, please correct me if I'm wrong, or you can comment directly in the files, using the github review interface:
1) Adding the BUILD file to help others, is ok, right?
2) MinimOsd_Extra/Func.h with my patch (I will revert the bit with MM)
3) MinimOsd_Extra/Vars.h with my patch
4) Released/FW_+_Char/MinimOsd_Extra_Uni.933MM-MAVLINK-release.hex if you want to test the code. I can revert it if you don't want it
5) you don't agree with the change to build.sh despite my rationale for it, so I will revert
6) libraries/SingleSerial was updated by git submodule automatically, without that things didn't build 

Please confirm what you want me to revert 
5?
4 + 5?
other?

If you tell me exactly what you want, I'll do it, I just don't want to guess wrong again :)

**Comment by night-ghost** [comment]
not 4 because this will be a new version so it with be rebuild.

You DON'T revert *all* changes in build.sh - this is exactly what I'm trying to explain. It is difficult to see the difference, but the change in behavior is fundamental.

**Comment by night-ghost** [comment]
well, I'll add this changes by hands some days after

**Comment by marcmerlin** [comment]
I understand what you said about trying into another tree and copying at the end, I will do this next time, but as you can guess, it's too late now since I can't unpublish anything from github unless I destroy the repository and start over.
I've however made another branch where I've reverted some things to make a smaller diff for you and an easier merge.
Please have a look at https://github.com/night-ghost/minimosd-extra/pull/195
I will close this pull and we can continue with #195

**Pull request closed without merging**
