### PR TITLE
Fix MWII serial protocol:

### PR DESCRIPTION
**Pull request by BondarenkoA**
- UART speed
- values of current, voltage, power
- reversed pitch in MWII
- GPS fix mode in MWII just 0 or 1
- switching flight modes
- speed up horizon drawing
- Actualize of MSP_STATUS message
- Dirty fix throttle

### CODE REVIEW

**Comment by BondarenkoA** [comment]
Proof for reversed pitch in MWII:
https://yandex.ru/images/search?text=multiwii%20config%20gui

MWII GPS fix states:
http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol
Message MSP_RAW_GPS

**Comment by night-ghost** [comment]
I did some changes by tour ideas, pls see latest version

**Comment by BondarenkoA** [comment]
I see. But you used not all of my fixes. That's why I brought proof links.
p.s. This PR is an example of why I think it is wrong to squash all commits into a single request.

**Comment by night-ghost** [comment]
>But you used not all of my fixes

there is a lots of non-functional changes like different spacing so it was rather hard to find what was missed.

**Comment by BondarenkoA** [comment]
> there is a lots of non-functional changes like different spacing so it was rather hard to find what was missed.
 
i'm realy sorry for it.  I agree that's a bad tone. But spacing was unreadable. Also the sheet of comments in cleanflight_core.h needs to be deleted.  imho, of course :)

**Comment by night-ghost** [comment]
>But spacing was unreadable.

maybe in your editor, not in mine. So best way is: 
1. create new branch and do what you want
2. do "diff -BburpN --skip-trailing-cr <dir1> <dir2>", it will contain only needed changes
3. create new branch and apply this diff
4. push and PR from this branch

**Comment by BondarenkoA** [comment]
i tested a last commit. Your fix of MWII uart speed does not worked. uart is started at 57600. You may check it with osciloscope, or just loks on func.h:getData().

**Pull request closed without merging**
